### ISSUE TITLE
Cover image for video 6 incorrect terms

### ISSUE THREAD

**Issue by Bshally** [wesbos/What-TheFlexbox-Site#1]
Not trying to be a weenie, but the cover image for vid 6 may be a bit confusing when it says "main axis when justify-content: column;". I think what was meant was when using justify-content on something with flex-direction: column.

Honestly doubt anybody would notice this unless they are watching these at 1am while drinking coffee like myself. I wouldn't normally add this issue but it gives me a chance to say thanks for the great work! It is a great series that lays out (pun not intended) flexbox in a logical and bite by bite way.  
<img width="1125" alt="screen shot 2015-09-17 at 1 31 31 am" src="https://cloud.githubusercontent.com/assets/3440317/9925651/e3d7c3ac-5cdb-11e5-8b34-61ced171d385.png">

**Comment by wesbos** [comment]
Hey! Thanks for letting me know - a few others have noticed it and I added in an annotation via youtube but I think it doesn't show up when embedded. I'll have to make a note about it on the site-  thanks!
